### ISSUE TITLE
Unable to Start Rate Provisioning Tool

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#228]
#### Page Path   http://45.24.188.171:7080/ui/Rate-Provisioning_Rate-Provisioning-Tool
Unable to started the Rate Provisioning Tool

#### Description of Issue
![image](https://cloud.githubusercontent.com/assets/18315382/19097042/7afbf8b8-8a6f-11e6-8fcd-adf62f6f86f6.png)

java.io.IOException: Server returned HTTP response code: 400 for URL: http://wpad.transnexus.com/wpad.dat
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection$10.run(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection$10.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.access$200(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection$9.run(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection$9.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessController.doPrivilegedWithCombiner(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at com.sun.deploy.net.proxy.AbstractAutoProxyHandler.getJSFileFromURL(Unknown Source)
	at com.sun.deploy.net.proxy.AbstractAutoProxyHandler.retrieveContentOfPACFile(Unknown Source)
	at com.sun.deploy.net.proxy.AbstractAutoProxyHandler.contructLegacyPACScript_16(Unknown Source)
	at com.sun.deploy.net.proxy.AbstractAutoProxyHandler.init(Unknown Source)
	at com.sun.deploy.net.proxy.SunAutoProxyHandler.init(Unknown Source)
	at com.sun.deploy.net.proxy.DynamicProxyManager.reset(Unknown Source)
	at com.sun.deploy.net.proxy.DeployProxySelector.reset(Unknown Source)
	at com.sun.javaws.Main.initializeExecutionEnvironment(Unknown Source)
	at com.sun.javaws.Main.continueInSecureThread(Unknown Source)
	at com.sun.javaws.Main.access$000(Unknown Source)
	at com.sun.javaws.Main$1.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.io.IOException: Server returned HTTP response code: 400 for URL: http://wpad.transnexus.com/wpad.dat
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.access$200(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection$9.run(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection$9.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessController.doPrivilegedWithCombiner(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getHeaderField(Unknown Source)
	at java.net.URLConnection.getContentType(Unknown Source)
	at com.sun.deploy.net.proxy.AbstractAutoProxyHandler.isSupportedINSFile(Unknown Source)
	... 11 more
CacheEntry[http://45.24.188.171:7080/lib/NexOSS_rate_provisioning_tool.jsp]: updateAvailable=false,lastModified=Wed Dec 31 19:00:00 EST 1969,length=-1
#### Unable to load resource: http://45.24.188.171:7080/lib/lib/commons-logging-1.1.jar

<?xml version="1.0" encoding="UTF-8"?>
<jnlp codebase="http://45.24.188.171:7080/lib" href="/lib/NexOSS_rate_provisioning_tool.jsp">
   <information>
      <title>NexOSS Rate Provisioning Tool</title>
      <vendor>TransNexus Inc.</vendor>
      <description>Bridge - Doing rate plan provisioning the fun way</description>
      <description kind="short">None</description>
      <offline-allowed/>
   </information>
   <resources>     
   	<jar href="Bridge.jar"/>   
   	<jar href="lib/commons-logging-1.1.jar"/>   
   	<jar href="lib/dom4j-1.6.1.jar"/>   
   	<jar href="lib/geronimo-stax-api_1.0_spec-1.0.jar"/>   
   	<jar href="lib/junit-3.8.1.jar"/>   
   	<jar href="lib/log4j-1.2.13.jar"/>   
   	<jar href="lib/ooxml-schemas-1.0.jar"/>   
   	<jar href="lib/poi-3.5-beta6-20090622.jar"/>   
   	<jar href="lib/poi-contrib-3.5-beta6-20090622.jar"/>   
   	<jar href="lib/poi-ooxml-3.5-beta6-20090622.jar"/>   
   	<jar href="lib/poi-scratchpad-3.5-beta6-20090622.jar"/>   
   	<jar href="lib/xmlbeans-2.3.0.jar"/>   
	<jar href="lib/commons-httpclient-3.1.jar"/>
	<jar href="lib/commons-codec_1.3.jar"/>
	<j2se version="1.6+"
		 href="http://java.sun.com/products/autodl/j2se" java-vm-args="-ea"/>
	<property name="jnlp.serverIpAddress" value="45.24.188.171"/>
	<property name="jnlp.serverPort" value="7080"/>
   </resources>
   <application-desc main-class="com.transnexus.bridge.main.Main"/>
   <security>
	<all-permissions/>
   </security>
</jnlp>

**Comment by JimDalton** [comment]
Same problem when downloading tool from .101.
http://45.24.188.171:7080/ui/Rate-Provisioning_Rate-Provisioning-Tool

![image](https://cloud.githubusercontent.com/assets/18315382/19097270/49dd3b96-8a71-11e6-9164-989ad16edf16.png)

com.sun.deploy.net.FailedDownloadException: Unable to load resource: http://172.16.4.101:7080/lib/NexOSS_rate_provisioning_tool.jsp
	at com.sun.deploy.net.DownloadEngine.actionDownload(Unknown Source)
	at com.sun.deploy.net.DownloadEngine.downloadResource(Unknown Source)
	at com.sun.deploy.cache.ResourceProviderImpl.getResource(Unknown Source)
	at com.sun.deploy.cache.ResourceProviderImpl.getResource(Unknown Source)
	at com.sun.javaws.Launcher.updateFinalLaunchDesc(Unknown Source)
	at com.sun.javaws.Launcher.prepareToLaunch(Unknown Source)
	at com.sun.javaws.Launcher.prepareToLaunch(Unknown Source)
	at com.sun.javaws.Launcher.launch(Unknown Source)
	at com.sun.javaws.Main.launchApp(Unknown Source)
	at com.sun.javaws.Main.continueInSecureThread(Unknown Source)
	at com.sun.javaws.Main.access$000(Unknown Source)
	at com.sun.javaws.Main$1.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by fenichelar** [comment]
@JimDalton This will unfortunately never work on .93, .100, .101, etc. It will only work on .32.

**Comment by DmitryIsakbayev** [comment]
@JimDalton you should not be able to start the rate provisioning tool from .100 or .101

The XML file from 45.24.188.171 looks correct, but I am not sure why it is expecting to find http://wpad.transnexus.com/wpad.dat (Web Proxy Auto-Discovery Protocol).

Can you start the app using the internal IP - 172.16.4.32?

**Comment by fenichelar** [comment]
@DmitryIsakbayev This can likely be ignored. http://wpad.DOMAIN_NAME/wpad.dat is the default address for WPAD (for applications requesting .dat format). Placing a config file in this location will allow proxies to be setup automatically. Not placing something there means there is no proxy.

**Comment by JimDalton** [comment]
Tested on .32 and it works as expected.  VPN into .32 and it worked as expected.
However, I could not download the rate provisioning tool with Waterfox.
