### ISSUE TITLE
Unable to open Rate Provisioning tool

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#326]
#### Description of Issue
I can download the rate provisioning tool from the new GUI.  But, when I try to open the rate provisioning tool, I get the following error.
java.io.IOException: Server returned HTTP response code: 500 for URL: http://172.16.4.101:7080/lib/NexOSS_rate_provisioning_tool.jsp
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.access$200(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection$9.run(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection$9.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessController.doPrivilegedWithCombiner(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at com.sun.deploy.net.HttpUtils.followRedirects(Unknown Source)

Java Console messages are:

java.io.IOException: Server returned HTTP response code: 403 for URL: http://wpad.transnexus.com/wpad.dat
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection$10.run(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection$10.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.access$200(Unknown Source)

When I navigate directly to the old UI on port 2080, and download the Rate Provisioning Tool, I get the following error. 
com.sun.deploy.net.JARSigningException: Found unsigned entry in resource: http://172.16.4.32:7080/lib/lib/log4j-1.2.13.jar
	at com.sun.javaws.security.SigningInfo.getCommonCodeSignersForJar(Unknown Source)
	at com.sun.javaws.security.SigningInfo.check(Unknown Source)
	at com.sun.javaws.security.JNLPSignedResourcesHelper.checkSignedResourcesHelper(Unknown Source)
	at com.sun.javaws.security.JNLPSignedResourcesHelper.checkSignedResources(Unknown Source)
	at com.sun.javaws.Launcher.prepareResources(Unknown Source)
	at com.sun.javaws.Launcher.prepareAllResources(Unknown Source)
	at com.sun.javaws.Launcher.prepareToLaunch(Unknown Source)

**Comment by DmitryIsakbayev** [comment]
Similar to #327 
The link to Java user interface and Java rate provisioning tool expect NexOSS to run on the same box as the new UI.  Since .93, .100, .101 and .103 do not have a local NexOSS (they point to .32), these links do not work.  The link works on .32

**Comment by JimDalton** [comment]
Ah, I should have remembered that!
However, I downloaded from http://172.16.4.32:7080/ui/Rate-Provisioning_Rate-Provisioning-Tool in the office and got the following errors.  Maybe something changed when the /directapi interface was addded? 
com.sun.deploy.net.JARSigningException: Found unsigned entry in resource: http://172.16.4.32:7080/lib/lib/log4j-1.2.13.jar
	at com.sun.javaws.security.SigningInfo.getCommonCodeSignersForJar(Unknown Source)
	at com.sun.javaws.security.SigningInfo.check(Unknown Source)
	at com.sun.javaws.security.JNLPSignedResourcesHelper.checkSignedResourcesHelper(Unknown Source)
	at com.sun.javaws.security.JNLPSignedResourcesHelper.checkSignedResources(Unknown Source)
	at com.sun.javaws.Launcher.prepareResources(Unknown Source)
	at com.sun.javaws.Launcher.prepareAllResources(Unknown Source)
	at com.sun.javaws.Launcher.prepareToLaunch(Unknown Source)
	at com.sun.javaws.Launcher.prepareToLaunch(Unknown Source)
	at com.sun.javaws.Launcher.launch(Unknown Source)
	at com.sun.javaws.Main.launchApp(Unknown Source)
	at com.sun.javaws.Main.continueInSecureThread(Unknown Source)
	at com.sun.javaws.Main.access$000(Unknown Source)
	at com.sun.javaws.Main$1.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by DmitryIsakbayev** [comment]
@JimDalton, I am not able to replicate this problem.  It should work from .101 now as well.

![1](https://cloud.githubusercontent.com/assets/14879700/21269204/dce170d2-c37f-11e6-9f57-0a71d9ee83d9.png)
